MACHINE = "edge-ai-nx-16g"
TMPDIR = "${TOPDIR}/tmp-mc-${BB_CURRENT_MC}"
MACHINEOVERRIDES =. "edge-ai-shared-runtime:"

# Let UEFI pass the DTB from the selected module-specific flash profile.
UBOOT_EXTLINUX_FDT = ""

CORE_IMAGE_EXTRA_INSTALL:append = " edge-ai-universal-runtime"
