#@TYPE: Machine
#@NAME: CompuLab Edge-AI with Nvidia Jetson Orin NANO 8GB (P3767-0003)
#@DESCRIPTION: Nvidia Jetson Orin NANO module in CompuLab Edge-AI board

require conf/machine/p3768-0000-p3767-0003.conf
require conf/machine/include/devkit-wifi.inc
require edge-ai.inc
