#@TYPE: Machine
#@NAME: CompuLab Edge-AI with Nvidia Jetson Orin NX 16GB (P3767-0000)
#@DESCRIPTION: Nvidia Jetson Orin NX module in CompuLab Edge-AI board

require conf/machine/p3768-0000-p3767-0000.conf
require edge-ai.inc
