#@TYPE: Machine
#@NAME: CompuLab Edge-AI with Nvidia Jetson Orin NX 8GB (P3767-0001)
#@DESCRIPTION: Nvidia Jetson Orin NX module in CompuLab Edge-AI board

require conf/machine/p3768-0000-p3767-0001.conf
require edge-ai.inc
